// flow-typed signature: 14b17eb0528418d79d4a23a797400927
// flow-typed version: <<STUB>>/eslint-plugin-emotion_v^9.2.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-emotion/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-emotion/src/rules/syntax-preference' {
  declare module.exports: any;
}

declare module 'eslint-plugin-emotion/test/rules/syntax-preference.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-emotion/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/src/index'>;
}
declare module 'eslint-plugin-emotion/src/rules/syntax-preference.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/src/rules/syntax-preference'>;
}
declare module 'eslint-plugin-emotion/test/rules/syntax-preference.test.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/test/rules/syntax-preference.test'>;
}
