// flow-typed signature: de858e1432350a476ff5bf5c525544fa
// flow-typed version: <<STUB>>/facepaint_v^1.2.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'facepaint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'facepaint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'facepaint/dist/facepaint.umd.min' {
  declare module.exports: any;
}

declare module 'facepaint/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'facepaint/dist/index.es' {
  declare module.exports: any;
}

declare module 'facepaint/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'facepaint/dist/facepaint.umd.min.js' {
  declare module.exports: $Exports<'facepaint/dist/facepaint.umd.min'>;
}
declare module 'facepaint/dist/index.cjs.js' {
  declare module.exports: $Exports<'facepaint/dist/index.cjs'>;
}
declare module 'facepaint/dist/index.es.js' {
  declare module.exports: $Exports<'facepaint/dist/index.es'>;
}
declare module 'facepaint/src/index.js' {
  declare module.exports: $Exports<'facepaint/src/index'>;
}
