// flow-typed signature: feaf1e8cd0f4c6b954d530cc02f53f9e
// flow-typed version: <<STUB>>/gatsby-plugin-remove-trailing-slashes_v^2.0.0-rc.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-remove-trailing-slashes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-remove-trailing-slashes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-remove-trailing-slashes/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-remove-trailing-slashes/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-remove-trailing-slashes/gatsby-node'>;
}
declare module 'gatsby-plugin-remove-trailing-slashes/index' {
  declare module.exports: $Exports<'gatsby-plugin-remove-trailing-slashes'>;
}
declare module 'gatsby-plugin-remove-trailing-slashes/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-remove-trailing-slashes'>;
}
