// flow-typed signature: 8d36a2e1b1a29f5213ce1b72b445d041
// flow-typed version: <<STUB>>/gatsby-plugin-nprogress_v^2.0.0-rc.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-nprogress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-nprogress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-nprogress/gatsby-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-nprogress/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-nprogress/gatsby-browser'>;
}
declare module 'gatsby-plugin-nprogress/index' {
  declare module.exports: $Exports<'gatsby-plugin-nprogress'>;
}
declare module 'gatsby-plugin-nprogress/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-nprogress'>;
}
