// flow-typed signature: e226a50e4212aab96944a916826e7095
// flow-typed version: <<STUB>>/gatsby-plugin-google-tagmanager_v^2.0.0-rc.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-google-tagmanager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-google-tagmanager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-google-tagmanager/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-google-tagmanager/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-tagmanager/gatsby-ssr'>;
}
declare module 'gatsby-plugin-google-tagmanager/index' {
  declare module.exports: $Exports<'gatsby-plugin-google-tagmanager'>;
}
declare module 'gatsby-plugin-google-tagmanager/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-tagmanager'>;
}
