// flow-typed signature: 4d3f77c20917ce370f7126c73def8147
// flow-typed version: <<STUB>>/gatsby-plugin-favicon_v^3.1.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-favicon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-favicon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-favicon/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-favicon/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-favicon/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-favicon/gatsby-node'>;
}
declare module 'gatsby-plugin-favicon/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-favicon/gatsby-ssr'>;
}
declare module 'gatsby-plugin-favicon/index' {
  declare module.exports: $Exports<'gatsby-plugin-favicon'>;
}
declare module 'gatsby-plugin-favicon/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-favicon'>;
}
