// flow-typed signature: 4d5fa326a8c8bdefa2d1ade34965e362
// flow-typed version: <<STUB>>/jest-emotion_v^9.2.7/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-emotion/dist/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/serializer' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/matchers' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-emotion/dist/index.js' {
  declare module.exports: $Exports<'jest-emotion/dist/index'>;
}
declare module 'jest-emotion/serializer.js' {
  declare module.exports: $Exports<'jest-emotion/serializer'>;
}
declare module 'jest-emotion/src/index.js' {
  declare module.exports: $Exports<'jest-emotion/src/index'>;
}
declare module 'jest-emotion/src/matchers.js' {
  declare module.exports: $Exports<'jest-emotion/src/matchers'>;
}
declare module 'jest-emotion/src/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion/src/replace-class-names'>;
}
declare module 'jest-emotion/src/utils.js' {
  declare module.exports: $Exports<'jest-emotion/src/utils'>;
}
