// flow-typed signature: b495a78f5b4f1fbf85eceffefdee00b5
// flow-typed version: <<STUB>>/react-anchor-link-smooth-scroll_v^1.0.11/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-anchor-link-smooth-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-anchor-link-smooth-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-anchor-link-smooth-scroll/lib/anchor-link' {
  declare module.exports: any;
}

declare module 'react-anchor-link-smooth-scroll/lib/anchor-link.min' {
  declare module.exports: any;
}

declare module 'react-anchor-link-smooth-scroll/src/anchor-link' {
  declare module.exports: any;
}

declare module 'react-anchor-link-smooth-scroll/src/index' {
  declare module.exports: any;
}

declare module 'react-anchor-link-smooth-scroll/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-anchor-link-smooth-scroll/lib/anchor-link.js' {
  declare module.exports: $Exports<'react-anchor-link-smooth-scroll/lib/anchor-link'>;
}
declare module 'react-anchor-link-smooth-scroll/lib/anchor-link.min.js' {
  declare module.exports: $Exports<'react-anchor-link-smooth-scroll/lib/anchor-link.min'>;
}
declare module 'react-anchor-link-smooth-scroll/src/anchor-link.js' {
  declare module.exports: $Exports<'react-anchor-link-smooth-scroll/src/anchor-link'>;
}
declare module 'react-anchor-link-smooth-scroll/src/index.js' {
  declare module.exports: $Exports<'react-anchor-link-smooth-scroll/src/index'>;
}
declare module 'react-anchor-link-smooth-scroll/webpack.config.js' {
  declare module.exports: $Exports<'react-anchor-link-smooth-scroll/webpack.config'>;
}
