// flow-typed signature: 7487b0e83b2a05c0dfb01c1ea6773fd3
// flow-typed version: <<STUB>>/system-components_v^3.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'system-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'system-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'system-components/dist/emotion' {
  declare module.exports: any;
}

declare module 'system-components/dist/index' {
  declare module.exports: any;
}

declare module 'system-components/dist/System' {
  declare module.exports: any;
}

declare module 'system-components/docs/index' {
  declare module.exports: any;
}

declare module 'system-components/emotion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'system-components/dist/emotion.js' {
  declare module.exports: $Exports<'system-components/dist/emotion'>;
}
declare module 'system-components/dist/index.js' {
  declare module.exports: $Exports<'system-components/dist/index'>;
}
declare module 'system-components/dist/System.js' {
  declare module.exports: $Exports<'system-components/dist/System'>;
}
declare module 'system-components/docs/index.js' {
  declare module.exports: $Exports<'system-components/docs/index'>;
}
declare module 'system-components/emotion.js' {
  declare module.exports: $Exports<'system-components/emotion'>;
}
