// flow-typed signature: 5e82e2d84139c817f72ec32cb688a1d5
// flow-typed version: <<STUB>>/typography-theme-bootstrap_v0.16.7/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography-theme-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography-theme-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography-theme-bootstrap/dist/index' {
  declare module.exports: any;
}

declare module 'typography-theme-bootstrap/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography-theme-bootstrap/dist/index.js' {
  declare module.exports: $Exports<'typography-theme-bootstrap/dist/index'>;
}
declare module 'typography-theme-bootstrap/src/index.js' {
  declare module.exports: $Exports<'typography-theme-bootstrap/src/index'>;
}
